version:  "2"
services:
  vehicle:
    image: vehicle
    pull_policy: if_not_present
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: vehicle
    depends_on: 
      - db
    ports:
      - "3000:3000" 
    networks:
      - mynet
  db:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mynet

networks:
  mynet: