# Generated by Django 5.0 on 2024-06-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='RegNum',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
